// src/strategy.rs
// Strategy definitions for backtesting arbitrage detection

use crate::types::{ArbType, PriceCents, SizeCents, kalshi_fee_cents};
use serde::{Deserialize, Serialize};

/// Market snapshot for strategy evaluation
#[derive(Debug, Clone, Copy)]
pub struct MarketSnapshot {
    pub market_id: u16,
    pub kalshi_yes: PriceCents,
    pub kalshi_no: PriceCents,
    pub kalshi_yes_size: SizeCents,
    pub kalshi_no_size: SizeCents,
    pub poly_yes: PriceCents,
    pub poly_no: PriceCents,
    pub poly_yes_size: SizeCents,
    pub poly_no_size: SizeCents,
    pub timestamp_ns: u64,
}

impl MarketSnapshot {
    /// Check if all prices are available
    pub fn has_all_prices(&self) -> bool {
        self.kalshi_yes > 0 && self.kalshi_no > 0 &&
        self.poly_yes > 0 && self.poly_no > 0
    }

    /// Calculate cost for each arb type (including fees)
    pub fn arb_costs(&self) -> ArbCosts {
        let k_yes_fee = kalshi_fee_cents(self.kalshi_yes);
        let k_no_fee = kalshi_fee_cents(self.kalshi_no);

        ArbCosts {
            poly_yes_kalshi_no: self.poly_yes + self.kalshi_no + k_no_fee,
            kalshi_yes_poly_no: self.kalshi_yes + k_yes_fee + self.poly_no,
            poly_only: self.poly_yes + self.poly_no,
            kalshi_only: self.kalshi_yes + k_yes_fee + self.kalshi_no + k_no_fee,
        }
    }

    /// Get minimum available size for an arb type
    pub fn min_size_for_arb(&self, arb_type: ArbType) -> SizeCents {
        match arb_type {
            ArbType::PolyYesKalshiNo => self.poly_yes_size.min(self.kalshi_no_size),
            ArbType::KalshiYesPolyNo => self.kalshi_yes_size.min(self.poly_no_size),
            ArbType::PolyOnly => self.poly_yes_size.min(self.poly_no_size),
            ArbType::KalshiOnly => self.kalshi_yes_size.min(self.kalshi_no_size),
        }
    }
}

/// Costs for each arbitrage type
#[derive(Debug, Clone, Copy)]
pub struct ArbCosts {
    pub poly_yes_kalshi_no: u16,
    pub kalshi_yes_poly_no: u16,
    pub poly_only: u16,
    pub kalshi_only: u16,
}

impl ArbCosts {
    /// Get cost for a specific arb type
    pub fn for_type(&self, arb_type: ArbType) -> u16 {
        match arb_type {
            ArbType::PolyYesKalshiNo => self.poly_yes_kalshi_no,
            ArbType::KalshiYesPolyNo => self.kalshi_yes_poly_no,
            ArbType::PolyOnly => self.poly_only,
            ArbType::KalshiOnly => self.kalshi_only,
        }
    }

    /// Get best (lowest) cost and its type
    pub fn best(&self) -> (u16, ArbType) {
        let mut best_cost = self.poly_yes_kalshi_no;
        let mut best_type = ArbType::PolyYesKalshiNo;

        if self.kalshi_yes_poly_no < best_cost {
            best_cost = self.kalshi_yes_poly_no;
            best_type = ArbType::KalshiYesPolyNo;
        }
        if self.poly_only < best_cost {
            best_cost = self.poly_only;
            best_type = ArbType::PolyOnly;
        }
        if self.kalshi_only < best_cost {
            best_cost = self.kalshi_only;
            best_type = ArbType::KalshiOnly;
        }

        (best_cost, best_type)
    }
}

/// Signal generated by a strategy
#[derive(Debug, Clone)]
pub struct StrategySignal {
    pub strategy_id: String,
    pub market_id: u16,
    pub arb_type: ArbType,
    pub cost_cents: u16,
    pub profit_cents: i16,
    pub yes_price: PriceCents,
    pub no_price: PriceCents,
    pub yes_size: SizeCents,
    pub no_size: SizeCents,
    pub confidence: f64,  // 0.0 - 1.0, strategy-specific confidence
    pub timestamp_ns: u64,
}

/// Strategy configuration - serializable for persistence
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyConfig {
    pub id: String,
    pub name: String,
    pub description: String,
    pub params: StrategyParams,
    pub enabled: bool,
}

/// Strategy parameters
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyParams {
    /// Maximum cost threshold in cents (100 = breakeven)
    pub threshold_cents: u16,

    /// Minimum profit in cents to trigger
    pub min_profit_cents: i16,

    /// Minimum liquidity (size) in cents on each side
    pub min_size_cents: u16,

    /// Only trigger on cross-platform arbs (not same-platform)
    pub cross_platform_only: bool,

    /// Only trigger on same-platform arbs
    pub same_platform_only: bool,

    /// Minimum price for YES side (filter extreme prices)
    pub min_yes_price: PriceCents,

    /// Maximum price for YES side
    pub max_yes_price: PriceCents,

    /// Minimum price for NO side
    pub min_no_price: PriceCents,

    /// Maximum price for NO side
    pub max_no_price: PriceCents,

    /// Prefer Polymarket leg (they have no fees)
    pub prefer_poly_leg: bool,

    /// Maximum Kalshi fee to accept (cents)
    pub max_kalshi_fee_cents: u16,
}

impl Default for StrategyParams {
    fn default() -> Self {
        Self {
            threshold_cents: 100,  // Breakeven
            min_profit_cents: 0,
            min_size_cents: 0,
            cross_platform_only: false,
            same_platform_only: false,
            min_yes_price: 1,
            max_yes_price: 99,
            min_no_price: 1,
            max_no_price: 99,
            prefer_poly_leg: false,
            max_kalshi_fee_cents: 10,
        }
    }
}

impl StrategyConfig {
    /// Evaluate this strategy against a market snapshot
    pub fn evaluate(&self, snapshot: &MarketSnapshot) -> Option<StrategySignal> {
        if !self.enabled || !snapshot.has_all_prices() {
            return None;
        }

        let costs = snapshot.arb_costs();
        let params = &self.params;

        // Find all arbs that pass the threshold
        let arb_types = [
            (ArbType::PolyYesKalshiNo, costs.poly_yes_kalshi_no, snapshot.poly_yes, snapshot.kalshi_no),
            (ArbType::KalshiYesPolyNo, costs.kalshi_yes_poly_no, snapshot.kalshi_yes, snapshot.poly_no),
            (ArbType::PolyOnly, costs.poly_only, snapshot.poly_yes, snapshot.poly_no),
            (ArbType::KalshiOnly, costs.kalshi_only, snapshot.kalshi_yes, snapshot.kalshi_no),
        ];

        let mut best_signal: Option<StrategySignal> = None;

        for (arb_type, cost, yes_price, no_price) in arb_types {
            // Threshold check
            if cost > params.threshold_cents {
                continue;
            }

            let profit = 100i16 - cost as i16;

            // Minimum profit check
            if profit < params.min_profit_cents {
                continue;
            }

            // Platform preference checks
            let is_cross = matches!(arb_type, ArbType::PolyYesKalshiNo | ArbType::KalshiYesPolyNo);
            if params.cross_platform_only && !is_cross {
                continue;
            }
            if params.same_platform_only && is_cross {
                continue;
            }

            // Price range checks
            if yes_price < params.min_yes_price || yes_price > params.max_yes_price {
                continue;
            }
            if no_price < params.min_no_price || no_price > params.max_no_price {
                continue;
            }

            // Liquidity check
            let min_size = snapshot.min_size_for_arb(arb_type);
            if min_size < params.min_size_cents {
                continue;
            }

            // Kalshi fee check
            let kalshi_fee = match arb_type {
                ArbType::PolyYesKalshiNo => kalshi_fee_cents(no_price),
                ArbType::KalshiYesPolyNo => kalshi_fee_cents(yes_price),
                ArbType::PolyOnly => 0,
                ArbType::KalshiOnly => kalshi_fee_cents(yes_price) + kalshi_fee_cents(no_price),
            };
            if kalshi_fee > params.max_kalshi_fee_cents {
                continue;
            }

            // Calculate confidence based on how far below threshold
            let confidence = if params.threshold_cents > 0 {
                ((params.threshold_cents - cost) as f64 / params.threshold_cents as f64).min(1.0)
            } else {
                1.0
            };

            // Prefer poly leg if configured
            let adjusted_confidence = if params.prefer_poly_leg {
                match arb_type {
                    ArbType::PolyYesKalshiNo | ArbType::PolyOnly => confidence * 1.1,
                    _ => confidence * 0.9,
                }
            } else {
                confidence
            };

            let (yes_size, no_size) = match arb_type {
                ArbType::PolyYesKalshiNo => (snapshot.poly_yes_size, snapshot.kalshi_no_size),
                ArbType::KalshiYesPolyNo => (snapshot.kalshi_yes_size, snapshot.poly_no_size),
                ArbType::PolyOnly => (snapshot.poly_yes_size, snapshot.poly_no_size),
                ArbType::KalshiOnly => (snapshot.kalshi_yes_size, snapshot.kalshi_no_size),
            };

            let signal = StrategySignal {
                strategy_id: self.id.clone(),
                market_id: snapshot.market_id,
                arb_type,
                cost_cents: cost,
                profit_cents: profit,
                yes_price,
                no_price,
                yes_size,
                no_size,
                confidence: adjusted_confidence.min(1.0),
                timestamp_ns: snapshot.timestamp_ns,
            };

            // Keep best signal (highest profit, or highest confidence if tied)
            if let Some(ref best) = best_signal {
                if signal.profit_cents > best.profit_cents ||
                   (signal.profit_cents == best.profit_cents && signal.confidence > best.confidence) {
                    best_signal = Some(signal);
                }
            } else {
                best_signal = Some(signal);
            }
        }

        best_signal
    }
}

/// Predefined strategy configurations for testing
pub fn default_strategies() -> Vec<StrategyConfig> {
    vec![
        // Strategy 1: Conservative (current default)
        StrategyConfig {
            id: "conservative".into(),
            name: "Conservative".into(),
            description: "Original strategy: 0.5% profit threshold, no filters".into(),
            params: StrategyParams {
                threshold_cents: 99,  // 1% profit required
                min_profit_cents: 1,
                ..Default::default()
            },
            enabled: true,
        },

        // Strategy 2: Aggressive threshold
        StrategyConfig {
            id: "aggressive".into(),
            name: "Aggressive".into(),
            description: "Lower threshold: triggers at breakeven, relies on favorable fills".into(),
            params: StrategyParams {
                threshold_cents: 100,  // Breakeven
                min_profit_cents: 0,
                ..Default::default()
            },
            enabled: true,
        },

        // Strategy 3: Very aggressive (negative edge)
        StrategyConfig {
            id: "very_aggressive".into(),
            name: "Very Aggressive".into(),
            description: "Accepts slight negative edge, betting on favorable execution".into(),
            params: StrategyParams {
                threshold_cents: 101,  // Accept 1% loss on paper
                min_profit_cents: -1,
                ..Default::default()
            },
            enabled: true,
        },

        // Strategy 4: Liquidity filtered
        StrategyConfig {
            id: "liquid_only".into(),
            name: "Liquidity Filtered".into(),
            description: "Only trades when sufficient liquidity ($5+ each side)".into(),
            params: StrategyParams {
                threshold_cents: 100,
                min_profit_cents: 0,
                min_size_cents: 500,  // $5 minimum
                ..Default::default()
            },
            enabled: true,
        },

        // Strategy 5: High liquidity + profit
        StrategyConfig {
            id: "high_conviction".into(),
            name: "High Conviction".into(),
            description: "High liquidity ($10+) AND minimum 1% profit".into(),
            params: StrategyParams {
                threshold_cents: 99,
                min_profit_cents: 1,
                min_size_cents: 1000,  // $10 minimum
                ..Default::default()
            },
            enabled: true,
        },

        // Strategy 6: Cross-platform only
        StrategyConfig {
            id: "cross_platform".into(),
            name: "Cross-Platform Only".into(),
            description: "Only Kalshi<->Poly arbs, no same-platform".into(),
            params: StrategyParams {
                threshold_cents: 100,
                min_profit_cents: 0,
                cross_platform_only: true,
                ..Default::default()
            },
            enabled: true,
        },

        // Strategy 7: Poly-only (no Kalshi fees)
        StrategyConfig {
            id: "poly_only".into(),
            name: "Polymarket Only".into(),
            description: "Same-platform Poly arbs only (zero fees)".into(),
            params: StrategyParams {
                threshold_cents: 100,
                min_profit_cents: 0,
                same_platform_only: true,
                cross_platform_only: false,
                ..Default::default()
            },
            enabled: true,
        },

        // Strategy 8: Mid-price focus
        StrategyConfig {
            id: "mid_price".into(),
            name: "Mid-Price Focus".into(),
            description: "Only 30-70 cent prices (avoid extremes)".into(),
            params: StrategyParams {
                threshold_cents: 100,
                min_profit_cents: 0,
                min_yes_price: 30,
                max_yes_price: 70,
                min_no_price: 30,
                max_no_price: 70,
                ..Default::default()
            },
            enabled: true,
        },

        // Strategy 9: Low fee preference
        StrategyConfig {
            id: "low_fee".into(),
            name: "Low Kalshi Fee".into(),
            description: "Only when Kalshi fee <= 1 cent (extreme prices)".into(),
            params: StrategyParams {
                threshold_cents: 100,
                min_profit_cents: 0,
                max_kalshi_fee_cents: 1,
                ..Default::default()
            },
            enabled: true,
        },

        // Strategy 10: Poly preference
        StrategyConfig {
            id: "poly_preferred".into(),
            name: "Poly Leg Preferred".into(),
            description: "Prefer arbs where Poly is the YES side (no fees on that leg)".into(),
            params: StrategyParams {
                threshold_cents: 100,
                min_profit_cents: 0,
                prefer_poly_leg: true,
                ..Default::default()
            },
            enabled: true,
        },

        // Strategy 11: Ultra conservative
        StrategyConfig {
            id: "ultra_conservative".into(),
            name: "Ultra Conservative".into(),
            description: "2%+ profit, high liquidity, mid-prices only".into(),
            params: StrategyParams {
                threshold_cents: 98,
                min_profit_cents: 2,
                min_size_cents: 500,
                min_yes_price: 25,
                max_yes_price: 75,
                min_no_price: 25,
                max_no_price: 75,
                ..Default::default()
            },
            enabled: true,
        },

        // Strategy 12: Near-miss tracker (for analysis)
        StrategyConfig {
            id: "near_miss".into(),
            name: "Near Miss Tracker".into(),
            description: "Tracks opportunities within 3% of breakeven (for analysis)".into(),
            params: StrategyParams {
                threshold_cents: 103,  // Within 3% of breakeven
                min_profit_cents: -3,
                ..Default::default()
            },
            enabled: true,
        },
    ]
}

/// Strategy manager - evaluates all strategies against market data
pub struct StrategyManager {
    strategies: Vec<StrategyConfig>,
}

impl StrategyManager {
    pub fn new(strategies: Vec<StrategyConfig>) -> Self {
        Self { strategies }
    }

    pub fn with_defaults() -> Self {
        Self::new(default_strategies())
    }

    /// Evaluate all enabled strategies against a market snapshot
    pub fn evaluate_all(&self, snapshot: &MarketSnapshot) -> Vec<StrategySignal> {
        self.strategies
            .iter()
            .filter(|s| s.enabled)
            .filter_map(|s| s.evaluate(snapshot))
            .collect()
    }

    /// Get strategy by ID
    pub fn get_strategy(&self, id: &str) -> Option<&StrategyConfig> {
        self.strategies.iter().find(|s| s.id == id)
    }

    /// Get all strategies
    pub fn strategies(&self) -> &[StrategyConfig] {
        &self.strategies
    }

    /// Enable/disable a strategy
    pub fn set_enabled(&mut self, id: &str, enabled: bool) -> bool {
        if let Some(s) = self.strategies.iter_mut().find(|s| s.id == id) {
            s.enabled = enabled;
            true
        } else {
            false
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_snapshot(k_yes: u16, k_no: u16, p_yes: u16, p_no: u16) -> MarketSnapshot {
        MarketSnapshot {
            market_id: 0,
            kalshi_yes: k_yes,
            kalshi_no: k_no,
            kalshi_yes_size: 1000,
            kalshi_no_size: 1000,
            poly_yes: p_yes,
            poly_no: p_no,
            poly_yes_size: 1000,
            poly_no_size: 1000,
            timestamp_ns: 0,
        }
    }

    #[test]
    fn test_arb_costs() {
        let snapshot = make_snapshot(50, 50, 40, 55);
        let costs = snapshot.arb_costs();

        // Poly YES (40) + Kalshi NO (50) + fee(50)=2 = 92
        assert_eq!(costs.poly_yes_kalshi_no, 92);

        // Kalshi YES (50) + fee(50)=2 + Poly NO (55) = 107
        assert_eq!(costs.kalshi_yes_poly_no, 107);

        // Poly only: 40 + 55 = 95
        assert_eq!(costs.poly_only, 95);

        // Kalshi only: 50 + 2 + 50 + 2 = 104
        assert_eq!(costs.kalshi_only, 104);
    }

    #[test]
    fn test_conservative_strategy() {
        let strategies = default_strategies();
        let conservative = strategies.iter().find(|s| s.id == "conservative").unwrap();

        // Clear arb: cost = 92, profit = 8
        let snapshot = make_snapshot(55, 50, 40, 60);
        let signal = conservative.evaluate(&snapshot);
        assert!(signal.is_some());
        let sig = signal.unwrap();
        assert_eq!(sig.profit_cents, 8);
    }

    #[test]
    fn test_liquidity_filter() {
        let strategies = default_strategies();
        let liquid = strategies.iter().find(|s| s.id == "liquid_only").unwrap();

        // Good arb but low liquidity
        let mut snapshot = make_snapshot(55, 50, 40, 60);
        snapshot.poly_yes_size = 100;  // Only $1 available

        let signal = liquid.evaluate(&snapshot);
        assert!(signal.is_none(), "Should reject low liquidity");

        // Same arb with good liquidity
        snapshot.poly_yes_size = 1000;
        let signal = liquid.evaluate(&snapshot);
        assert!(signal.is_some());
    }

    #[test]
    fn test_strategy_manager() {
        let manager = StrategyManager::with_defaults();

        let snapshot = make_snapshot(55, 50, 40, 60);
        let signals = manager.evaluate_all(&snapshot);

        // Multiple strategies should trigger on a clear arb
        assert!(!signals.is_empty());
    }
}
